# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '35 10 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v10
      with:
        days-before-stale: 90
        days-before-close: 7
        stale-issue-message: 'This issue has been automatically marked as stale due to inactivity. If it is still valid please comment within 7 days or it will be auto-closed.'
        close-issue-message: 'Closing this issue due to prolonged inactivity.'
        # Disabled PR Closing for now, but pre-staged the settings
        days-before-pr-stale: -1
        days-before-pr-close: -1
        operations-per-run: 100
        stale-pr-message: "This PR appears to be stale.  If it is still valid please comment within 14 days or it will be auto-closed."
        close-pr-message: "This PR was closed as stale."
        exempt-issue-labels: 'keep-open,enhancement,critical,dependencies,documentation'
